version: '3'

services:
  database:
    image: postgres:10.7
    environment:
      POSTGRES_DB: "traffic_stops_nc"
      POSTGRES_PASSWORD: "traffic_stops_nc"
      POSTGRES_USER: "traffic_stops_nc"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./data:/data

volumes:
  postgres_data:
