version: '3'

services:
  database:
    image: postgres:10.7
    environment:
      POSTGRES_DB: "traffic_stops_nc"
      POSTGRES_PASSWORD: "traffic_stops_nc"
      POSTGRES_USER: "traffic_stops_nc"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./data:/data

  jupyter:
    build: ./docker/jupyter
    ports:
      - "8888:8888"
    command: jupyter lab --port=8888 --no-browser --LabApp.token=""
    volumes:
      - ./:/home/jovyan/

volumes:
  postgres_data:
